# build environment
FROM node:14-alpine as build
WORKDIR /app
COPY package.json package-lock.json .env.production ./
RUN npm ci --silent
COPY public ./public
COPY src ./src
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]